-- AlterTable
ALTER TABLE "BillingDetails" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "lastname" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "company" DROP NOT NULL,
ALTER COLUMN "rfc" DROP NOT NULL,
ALTER COLUMN "phone" DROP NOT NULL;
